name: OHRI Dev Deployment

on:
  push:
    branches:
      - dev-deploy
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  server_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Copy files to /home/runner/
        run: |
          ls -la -t
          cp -r $GITHUB_WORKSPACE/.ssh/ /home/runner/

      - name: List contents of /home/runner/
        run: ls -la /home/runner/

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.LL_SSH_PRIVATE_KEY }}

      - name: Check SSH to remote OHRI Dev status
        run: |
            ssh-keygen -R 172.19.0.16      
  
  server_connection_reports:
    runs-on: ubuntu-latest

    steps:
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.LL_SSH_PRIVATE_KEY }}     
       
      - name: SSH to remote OHRI Dev server 
        run: | 
            ssh -o StrictHostKeyChecking=no -T llemos@20.172.182.46 -p 2202 " cd /opt ls -la -t "
           
      # - name: SSH to remote OHRI Dev server via jump host
      #   run: |
      #       ssh llemos@172.19.0.16 -p 2216 -J llemos@reports.globalhealthapp.net:2202

  server_connection_dev:
      runs-on: ubuntu-latest

      steps:      
        - name: SSH to remote OHRI Dev server 
          run: | 
            ssh -v -o StrictHostKeyChecking=no -T llemos@172.19.0.16 -p 2216 -J llemos@20.172.182.46:2202
            ls -la -t
            cd /opt 
            ls -la -t 
        
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.8.0

        with:
          ssh-private-key: ${{ secrets.LL_SSH_PRIVATE_KEY }}

      - name: SSH to remote OHRI Dev server via jump host
        run: |
          ssh -p 2216 \
              -o "UserKnownHostsFile=/dev/null" \
              -o "StrictHostKeyChecking=no" \
              -o "ProxyCommand=ssh -o StrictHostKeyChecking=no -W %h:%p llemos@20.172.182.46 -p 2202" \
              llemos@172.19.0.16 "\
              docker-compose -f docker-compose-ohri-dev.yml pull && \
              docker-compose -f docker-compose-ohri-dev.yml down && \
              docker-compose -f docker-compose-ohri-dev.yml up -d"
          
