name: OHRI Dev Deployment

on:
  push:
    branches:
      - dev-deploy
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  server_status:
    runs-on: ubuntu-latest

    steps:
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.LL_SSH_PRIVATE_KEY }}
      - name: Collect Git and SSH config files in a directory that is part of the Docker build context
        run: |
          mkdir root-config
          cp -r ~/.gitconfig  ~/.ssh root-config/

      - name: Check SSH to remote OHRI Dev status
        run: |
            ssh-keygen -R 172.19.0.16      
  
  server_connection:
    runs-on: ubuntu-latest

    steps:
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.LL_SSH_PRIVATE_KEY }}     
       
      - name: SSH to remote OHRI Dev server 
        run: |
            ssh -o "ProxyJump=llemos@reports.globalhealthapp.net:2202"
      - name: SSH to remote OHRI Dev server via jump host
        run: |
            ssh llemos@172.19.0.16 -p 2216 -J llemos@reports.globalhealthapp.net:2202
              
        
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.8.0

        with:
          ssh-private-key: ${{ secrets.LL_SSH_PRIVATE_KEY }}

      - name: SSH to remote OHRI Dev server via jump host
        run: |
          ssh -o "ProxyJump=llemos@reports.globalhealthapp.net:2202" -p 2216 llemos@172.19.0.16 