name: OHRI Distro with O3 Images - Docker Deployment

on:
  push:
    branches:
      - master-ohri
      - dev

    # Publish semver tags as releases.
  pull_request:
    types: [opened, synchronize, closed]
  release:
    types:
      - created
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          java: [ '8', '11' ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build and Test
        run: mvn --batch-mode --update-snapshots --activate-profiles validator clean package

  docker_setup:
    runs-on: ubuntu-latest
    
    if: github.event_name == 'push'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  docker_distro_backend:
    runs-on: ubuntu-latest
    needs: docker_setup

    if: (github.event_name == 'push' ||  github.event.pull_request.merged) || (github.event.changes != null && contains(github.event.changes, 'distro/'))

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ohri-distro-backend-2_6:latest,${{ secrets.DOCKERHUB_USERNAME }}/ohri-distro-backend-2_6:ci_${{ github.run_number }}
          cache-from: type=inline,ref=user/app:buildcache
          cache-to: type=inline,ref=user/app:buildcache,mode=max

  docker_distro_frontend:
    runs-on: ubuntu-latest
    needs: docker_setup

    if: (github.event_name == 'push' ||  github.event.pull_request.merged) && (github.event.changes != null && contains(github.event.changes, 'frontend/'))

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ohri-distro-frontend:latest,${{ secrets.DOCKERHUB_USERNAME }}/ohri-distro-frontend:ci_${{ github.run_number }}
          cache-from: type=inline,ref=user/app:buildcache
          cache-to: type=inline,ref=user/app:buildcache,mode=max

  docker_distro_gateway:
    runs-on: ubuntu-latest
    needs: docker_setup

    if: (github.event_name == 'push' ||  github.event.pull_request.merged) || (github.event.changes != null && contains(github.event.changes, 'gateway/'))

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: ./gateway
          file: ./gateway/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ohri-distro_proxy:latest,${{ secrets.DOCKERHUB_USERNAME }}/ohri-distro_proxy:ci_${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Save image digest
        run: echo "::set-output name=image::${{ steps.build-and-push.output.digest }}"

  dev_server_status:
    if: github.ref == 'refs/heads/dev-deploy' 
    runs-on: ubuntu-latest

    steps:
      - name: Wait for 5 minutos - Let Images reflect on Docker Hub
        run: sleep 300
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Copy files to /home/runner/
        run: |
          ls -la -t
          cp -r $GITHUB_WORKSPACE/.ssh/ /home/runner/

      - name: List contents of /home/runner/
        run: ls -la /home/runner/

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.LL_SSH_PRIVATE_KEY }}

      - name: Check SSH to remote OHRI Dev status
        run: |
            ssh-keygen -R 172.19.0.16      
            
  dev_server_connection_dev:
      runs-on: ubuntu-latest
      needs: dev_server_status
      steps:      
        - name: SSH to remote OHRI Dev server 
          run: | 
            ssh -o StrictHostKeyChecking=no -T llemos@172.19.0.16 -p 2216 -J llemos@20.172.182.46 -p 2202
            ls -la -t  && \
            cd /opt && \
            ls -la -t 
        
  dev_deploy:
    runs-on: ubuntu-latest
    needs: dev_server_status

    if: (github.event_name == 'push' ||  github.event.pull_request.merged) 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.8.0

        with:
          ssh-private-key: ${{ secrets.LL_SSH_PRIVATE_KEY }}

      - name: SSH to remote OHRI Dev server via jump host
        run: |
          ssh -p 2216 \
              -o "UserKnownHostsFile=/dev/null" \
              -o "StrictHostKeyChecking=no" \
              -o "ProxyCommand=ssh -o StrictHostKeyChecking=no -W %h:%p llemos@20.172.182.46 -p 2202" \
              llemos@172.19.0.16 "\
              cd /opt && \
              docker compose -f docker-compose-ohri-dev.yml pull && \
              docker compose -f docker-compose-ohri-dev.yml stop && \
              docker compose -f docker-compose-ohri-dev.yml up -d"
                  
  working_server_status:
    if: github.ref == 'refs/heads/working-deploy' 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Copy files to /home/runner/
        run: |
          ls -la -t
          cp -r $GITHUB_WORKSPACE/.ssh/ /home/runner/

      - name: List contents of /home/runner/
        run: ls -la /home/runner/

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.LL_SSH_PRIVATE_KEY }}

      - name: Check SSH to remote OHRI Dev status
        run: |
            ssh-keygen -R 172.19.0.17      
            
  working_server_connection_dev:
      runs-on: ubuntu-latest
      needs: working_server_status

      steps:      
        - name: SSH to remote OHRI Dev server 
          run: | 
            ssh -o StrictHostKeyChecking=no -T llemos@172.19.0.17 -p 2217 -J llemos@20.172.182.46 -p 2202
            ls -la -t  && \
            cd /opt && \
            ls -la -t 
          
  working_deploy:
    runs-on: ubuntu-latest
    needs: working_server_status

    if: (github.event_name == 'push' ||  github.event.pull_request.merged) 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.8.0

        with:
          ssh-private-key: ${{ secrets.LL_SSH_PRIVATE_KEY }}

      - name: SSH to remote OHRI Dev server via jump host
        run: |
          ssh -p 2217 \
              -o "UserKnownHostsFile=/dev/null" \
              -o "StrictHostKeyChecking=no" \
              -o "ProxyCommand=ssh -o StrictHostKeyChecking=no -W %h:%p llemos@20.172.182.46 -p 2202" \
              llemos@172.19.0.17 "\
              cd /opt && \
              docker compose -f docker-compose-ohri-working.yml pull && \
              docker compose -f docker-compose-ohri-working.yml stop && \
              docker compose -f docker-compose-ohri-working.yml up -d"